/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import clases.Cajeros;
import clases.UsuarioLV;
import javax.swing.JOptionPane;

/**
 *
 * @author HUAWEI PC
 */
public class RegistroCajeross extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClientes
     */
    public RegistroCajeross() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreE = new javax.swing.JLabel();
        lblCorreoE = new javax.swing.JLabel();
        lblContraseñaE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEdadE = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        txtNombreE = new javax.swing.JTextField();
        txtCorreoE = new javax.swing.JTextField();
        txtEdadE = new javax.swing.JTextField();
        txtContraseñaE = new javax.swing.JPasswordField();
        txtSucursal = new javax.swing.JTextField();
        btnRegistarE = new javax.swing.JButton();
        btnModificarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsuarioE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¡Sea Bienvenido/a al registro de");

        jLabel2.setText("cajeros/as de nuestras sucursales");

        lblNombreE.setText("Ingrese su nombre completo");

        lblCorreoE.setText("Ingrese su correo");

        lblContraseñaE.setText("Ingrese su contraseña");

        jLabel6.setText("Burguesas");

        jLabel7.setText("Fide");

        lblEdadE.setText("Ingrese su edad");

        lblSucursal.setText("Ingrese la sucursal");

        btnRegistarE.setText("Registrar");
        btnRegistarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarEActionPerformed(evt);
            }
        });

        btnModificarE.setText("Modificar");
        btnModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEActionPerformed(evt);
            }
        });

        btnEliminarE.setText("Eliminar");

        jLabel3.setText("Ingrese el usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseñaE, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseñaE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistarE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminarE))
                            .addComponent(lblSucursal)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuarioE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdadE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreoE, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(lblNombreE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreoE)))
                .addGap(18, 18, 18)
                .addComponent(lblSucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdadE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblContraseñaE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContraseñaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistarE)
                    .addComponent(btnModificarE)
                    .addComponent(btnEliminarE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarEActionPerformed
        if (!txtNombreE.getText().isEmpty()&&!txtCorreoE.getText().isEmpty()&&
                !txtSucursal.getText().isEmpty()&&!txtEdadE.getText().isEmpty()&&
                !txtUsuarioE.getText().isEmpty()&&!txtContraseñaE.getText().isEmpty()) {
Cajeros usuario=new Cajeros(txtNombreE.getText(), txtCorreoE.getText(), txtSucursal.getText(),txtEdadE.getText(), txtUsuarioE.getText(), txtContraseñaE.getText());            
            if (UsuarioLV.insertar(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuario Registrado con éxito");
                
            }else{
                JOptionPane.showMessageDialog(null, "Usuario ya existente");
                
            }
        }
        
    }//GEN-LAST:event_btnRegistarEActionPerformed

    private void btnModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEActionPerformed
         if (!txtNombreE.getText().isEmpty()&&!txtCorreoE.getText().isEmpty()&&
                !txtSucursal.getText().isEmpty()&&!txtEdadE.getText().isEmpty()&&
                !txtUsuarioE.getText().isEmpty()&&!txtContraseñaE.getText().isEmpty()) {
Cajeros usuario=new Cajeros(txtNombreE.getText(), txtCorreoE.getText(), txtSucursal.getText(),txtEdadE.getText(), txtUsuarioE.getText(), txtContraseñaE.getText());            
            if (UsuarioLV.modificar(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuario Registrado con éxito");
                
            }else{
                JOptionPane.showMessageDialog(null, "Usuario ya existente");
                
            }
        }
    }//GEN-LAST:event_btnModificarEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCajeross.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCajeross.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCajeross.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCajeross.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCajeross().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnModificarE;
    private javax.swing.JButton btnRegistarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblContraseñaE;
    private javax.swing.JLabel lblCorreoE;
    private javax.swing.JLabel lblEdadE;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JPasswordField txtContraseñaE;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtEdadE;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtUsuarioE;
    // End of variables declaration//GEN-END:variables
}
