package Restaurante;


import Restaurante.FacturaBebidas;
import java.io.File;
import javax.swing.*;  //Comodin Buscar en este paquete
import java.io.*; //Entrada y salida de datos
import javax.swing.JOptionPane;
import java.net.*;
import java.io.*;

public class VenMenu extends javax.swing.JFrame {

    
    /**
     * Creates new form VenMenu
     */
    private VentanaEntregas pedido;
    public VenMenu() {
        initComponents();
          pedido = new VentanaEntregas(); //crear con constructor
        pedido.setVisible(true);// la hago visible
        
        //////////////////////////////
        setLocationRelativeTo(this); //Centra la ventana en la pantalla
        setTitle("Menu");//Asigna titulo a la ventana 
    }
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTamaño = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JTabbedPane();
        tabBebidas = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        GuiLabelTipoBebida = new javax.swing.JLabel();
        GuiLabelCliente1 = new javax.swing.JLabel();
        GuiTxtNombre = new javax.swing.JTextField();
        GuiComboxBebida = new javax.swing.JComboBox<>();
        GuiLabelMedida = new javax.swing.JLabel();
        GuiLabelTamaño = new javax.swing.JLabel();
        GuiRadioButtonGrande = new javax.swing.JRadioButton();
        GuiRadioButtonPequeño = new javax.swing.JRadioButton();
        GuiRadioButtonMediano = new javax.swing.JRadioButton();
        GuiSliderMedida = new javax.swing.JSlider();
        tabDesayuno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        guiHuevosTostada = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        guiHuevosSalchichaTostada = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        guiPinto = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        guiEnchiladas = new javax.swing.JCheckBox();
        BottonOrden = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        guiHuevosPanquequeTocinetas = new javax.swing.JCheckBox();
        huevosyTostada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tabAlmuerzo = new javax.swing.JPanel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        guiPolloAzadoIma = new javax.swing.JLabel();
        guiArrosPolloIma = new javax.swing.JLabel();
        guiLasanaIma = new javax.swing.JLabel();
        guihamburgesaIma = new javax.swing.JLabel();
        guiPezcadoIma = new javax.swing.JLabel();
        guiOrdenarAlmuerzo = new javax.swing.JButton();
        guiPezcado = new javax.swing.JCheckBox();
        guiPollo = new javax.swing.JCheckBox();
        guiArrozPollo = new javax.swing.JCheckBox();
        guiLasana = new javax.swing.JCheckBox();
        guihamburgesa = new javax.swing.JCheckBox();
        tabFactura = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        GuiBottonCargarOrden = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GuiTArDetalle = new javax.swing.JTextArea();
        tabDelivery = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jlabl2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        guienviar = new javax.swing.JButton();
        guiLimitacion = new javax.swing.JSlider();
        guiTiempo = new javax.swing.JSlider();
        guiNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        guiConversacion = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        guiEnviarOrden = new javax.swing.JButton();
        guiEnviar1 = new javax.swing.JButton();
        RecibirOrden = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(new javax.swing.border.MatteBorder(null));

        panelMenu.setForeground(new java.awt.Color(102, 102, 102));
        panelMenu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        GuiLabelTipoBebida.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        GuiLabelTipoBebida.setForeground(new java.awt.Color(0, 153, 153));
        GuiLabelTipoBebida.setText("Tipo de bebida:");

        GuiLabelCliente1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        GuiLabelCliente1.setForeground(new java.awt.Color(0, 153, 153));
        GuiLabelCliente1.setText("Cliente:");

        GuiTxtNombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        GuiComboxBebida.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        GuiComboxBebida.setForeground(new java.awt.Color(51, 51, 51));
        GuiComboxBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limonada.", "Té helado.", "Café frappé", "Granizados de frutas.", "Horchata.", "Arcoiris de gelatinas.", "Vinos veraniegos.", "Cervesa Artesanal", "Cervesa Nacional" }));
        GuiComboxBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiComboxBebidaActionPerformed(evt);
            }
        });

        GuiLabelMedida.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        GuiLabelMedida.setForeground(new java.awt.Color(0, 153, 153));
        GuiLabelMedida.setText("Medida:");

        GuiLabelTamaño.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        GuiLabelTamaño.setForeground(new java.awt.Color(0, 153, 153));
        GuiLabelTamaño.setText("Tamaño:");

        GuiRadioButtonGrande.setBackground(new java.awt.Color(255, 255, 255));
        GrupoTamaño.add(GuiRadioButtonGrande);
        GuiRadioButtonGrande.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GuiRadioButtonGrande.setForeground(new java.awt.Color(0, 153, 153));
        GuiRadioButtonGrande.setText("Grande");

        GuiRadioButtonPequeño.setBackground(new java.awt.Color(255, 255, 255));
        GrupoTamaño.add(GuiRadioButtonPequeño);
        GuiRadioButtonPequeño.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GuiRadioButtonPequeño.setForeground(new java.awt.Color(0, 153, 153));
        GuiRadioButtonPequeño.setText("Pequeña");

        GuiRadioButtonMediano.setBackground(new java.awt.Color(255, 255, 255));
        GrupoTamaño.add(GuiRadioButtonMediano);
        GuiRadioButtonMediano.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GuiRadioButtonMediano.setForeground(new java.awt.Color(0, 153, 153));
        GuiRadioButtonMediano.setText("Mediana");

        GuiSliderMedida.setBackground(new java.awt.Color(0, 153, 153));
        GuiSliderMedida.setForeground(new java.awt.Color(0, 153, 153));
        GuiSliderMedida.setMajorTickSpacing(100);
        GuiSliderMedida.setMaximum(500);
        GuiSliderMedida.setMinimum(100);
        GuiSliderMedida.setPaintLabels(true);
        GuiSliderMedida.setPaintTicks(true);
        GuiSliderMedida.setValue(50);

        javax.swing.GroupLayout tabBebidasLayout = new javax.swing.GroupLayout(tabBebidas);
        tabBebidas.setLayout(tabBebidasLayout);
        tabBebidasLayout.setHorizontalGroup(
            tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabBebidasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBebidasLayout.createSequentialGroup()
                        .addComponent(GuiLabelTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuiComboxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GuiLabelTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabBebidasLayout.createSequentialGroup()
                        .addComponent(GuiLabelMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuiSliderMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBebidasLayout.createSequentialGroup()
                        .addComponent(GuiRadioButtonGrande)
                        .addGap(40, 40, 40)
                        .addComponent(GuiRadioButtonMediano)
                        .addGap(57, 57, 57)
                        .addComponent(GuiRadioButtonPequeño))
                    .addGroup(tabBebidasLayout.createSequentialGroup()
                        .addComponent(GuiLabelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(GuiTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1264, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabBebidasLayout.setVerticalGroup(
            tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 2754, Short.MAX_VALUE)
            .addGroup(tabBebidasLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuiLabelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuiTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuiLabelTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuiComboxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(GuiLabelTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuiRadioButtonGrande)
                    .addComponent(GuiRadioButtonMediano)
                    .addComponent(GuiRadioButtonPequeño))
                .addGap(18, 18, 18)
                .addGroup(tabBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuiLabelMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuiSliderMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2441, Short.MAX_VALUE))
        );

        panelMenu.addTab("Bebidas", tabBebidas);

        guiHuevosTostada.setBackground(new java.awt.Color(255, 255, 255));
        guiHuevosTostada.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guiHuevosTostada.setForeground(new java.awt.Color(153, 153, 153));
        guiHuevosTostada.setText("Huevos y tostadas");
        guiHuevosTostada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiHuevosTostadaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/Salchica huevo y tostada.jpg"))); // NOI18N

        guiHuevosSalchichaTostada.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guiHuevosSalchichaTostada.setForeground(new java.awt.Color(0, 51, 51));
        guiHuevosSalchichaTostada.setText("Huevos, salchichas, tostadas, tomate y ensaladas");
        guiHuevosSalchichaTostada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiHuevosSalchichaTostadaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/Pinto con huevo y pan.jpg"))); // NOI18N

        guiPinto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guiPinto.setForeground(new java.awt.Color(0, 51, 51));
        guiPinto.setText("Pinto huevos y pan con ajo");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/enchilada de pollo.jpg"))); // NOI18N

        guiEnchiladas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guiEnchiladas.setText("Pollo enchiladas pan y con queso");

        BottonOrden.setBackground(new java.awt.Color(153, 255, 0));
        BottonOrden.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BottonOrden.setForeground(new java.awt.Color(51, 255, 0));
        BottonOrden.setText("Ordenar");
        BottonOrden.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 51)));
        BottonOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonOrdenActionPerformed(evt);
            }
        });

        guiHuevosPanquequeTocinetas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guiHuevosPanquequeTocinetas.setText("Papas huevos pancake tocinetas");
        guiHuevosPanquequeTocinetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiHuevosPanquequeTocinetasActionPerformed(evt);
            }
        });

        huevosyTostada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/Huevos y tostada.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/panqueque y tocineta.jpg"))); // NOI18N

        javax.swing.GroupLayout tabDesayunoLayout = new javax.swing.GroupLayout(tabDesayuno);
        tabDesayuno.setLayout(tabDesayunoLayout);
        tabDesayunoLayout.setHorizontalGroup(
            tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDesayunoLayout.createSequentialGroup()
                .addGroup(tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiHuevosTostada)
                    .addComponent(huevosyTostada, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiHuevosSalchichaTostada)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiEnchiladas)
                    .addComponent(guiPinto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1436, Short.MAX_VALUE))
            .addGroup(tabDesayunoLayout.createSequentialGroup()
                .addGroup(tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDesayunoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabDesayunoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(tabDesayunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guiHuevosPanquequeTocinetas))
                    .addGroup(tabDesayunoLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(BottonOrden)))
                .addContainerGap(1215, Short.MAX_VALUE))
        );
        tabDesayunoLayout.setVerticalGroup(
            tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDesayunoLayout.createSequentialGroup()
                .addComponent(huevosyTostada, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guiHuevosTostada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guiHuevosSalchichaTostada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guiPinto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiEnchiladas)
                .addGroup(tabDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDesayunoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8))
                    .addGroup(tabDesayunoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(guiHuevosPanquequeTocinetas)
                .addGap(63, 63, 63)
                .addComponent(BottonOrden)
                .addGap(235, 235, 235)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panelMenu.addTab("Desayuno", tabDesayuno);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        guiPolloAzadoIma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/po azado.PNG"))); // NOI18N

        guiArrosPolloIma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/arroz po.PNG"))); // NOI18N

        guiLasanaIma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/lasana2.PNG"))); // NOI18N

        guihamburgesaIma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/hambur con papas.PNG"))); // NOI18N

        guiPezcadoIma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/arroz con pesacado.jpg"))); // NOI18N

        guiOrdenarAlmuerzo.setText("Ordenar");
        guiOrdenarAlmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiOrdenarAlmuerzoActionPerformed(evt);
            }
        });

        guiPezcado.setText("Pezcado, arroz, ensalada, yuca");
        guiPezcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiPezcadoActionPerformed(evt);
            }
        });

        guiPollo.setText("Alas de porllo a la parrilla");

        guiArrozPollo.setText("Arroz con pollo");

        guiLasana.setText("Lasaña");

        guihamburgesa.setText("Hamburguesa con papas");

        javax.swing.GroupLayout tabAlmuerzoLayout = new javax.swing.GroupLayout(tabAlmuerzo);
        tabAlmuerzo.setLayout(tabAlmuerzoLayout);
        tabAlmuerzoLayout.setHorizontalGroup(
            tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAlmuerzoLayout.createSequentialGroup()
                .addGroup(tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAlmuerzoLayout.createSequentialGroup()
                        .addGroup(tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guiPolloAzadoIma, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiPezcado))
                        .addGap(164, 164, 164)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(guiLasanaIma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(guiArrosPolloIma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addComponent(guihamburgesaIma, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiPezcadoIma, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabAlmuerzoLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(guiOrdenarAlmuerzo))
                    .addComponent(guiPollo)
                    .addComponent(guiArrozPollo)
                    .addComponent(guiLasana)
                    .addComponent(guihamburgesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1303, Short.MAX_VALUE)
                .addComponent(jScrollBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabAlmuerzoLayout.setVerticalGroup(
            tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tabAlmuerzoLayout.createSequentialGroup()
                .addGroup(tabAlmuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAlmuerzoLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAlmuerzoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(guiPezcadoIma, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(guiPezcado)
                        .addGap(53, 53, 53)
                        .addComponent(guiPolloAzadoIma)))
                .addGap(37, 37, 37)
                .addComponent(guiPollo)
                .addGap(36, 36, 36)
                .addComponent(guiArrosPolloIma)
                .addGap(18, 18, 18)
                .addComponent(guiArrozPollo)
                .addGap(45, 45, 45)
                .addComponent(guiLasanaIma, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(guiLasana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guihamburgesaIma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guihamburgesa)
                .addGap(31, 31, 31)
                .addComponent(guiOrdenarAlmuerzo)
                .addGap(23, 23, 23))
        );

        panelMenu.addTab("Almuerzo", tabAlmuerzo);

        GuiBottonCargarOrden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GuiBottonCargarOrden.setForeground(new java.awt.Color(0, 153, 153));
        GuiBottonCargarOrden.setText("Ver Orden");
        GuiBottonCargarOrden.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        GuiBottonCargarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiBottonCargarOrdenActionPerformed(evt);
            }
        });

        GuiTArDetalle.setColumns(20);
        GuiTArDetalle.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        GuiTArDetalle.setRows(5);
        jScrollPane2.setViewportView(GuiTArDetalle);

        javax.swing.GroupLayout tabFacturaLayout = new javax.swing.GroupLayout(tabFactura);
        tabFactura.setLayout(tabFacturaLayout);
        tabFacturaLayout.setHorizontalGroup(
            tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFacturaLayout.createSequentialGroup()
                .addGroup(tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFacturaLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabFacturaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabFacturaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(GuiBottonCargarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1320, Short.MAX_VALUE))
        );
        tabFacturaLayout.setVerticalGroup(
            tabFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFacturaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(82, 82, 82)
                .addComponent(GuiBottonCargarOrden)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2372, Short.MAX_VALUE))
        );

        panelMenu.addTab("Factura Ordenes", tabFactura);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Nombre Repartidor");

        jlabl2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlabl2.setForeground(new java.awt.Color(0, 153, 153));
        jlabl2.setText("Tiempo");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Demorar");

        guienviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/Botton delivery.png"))); // NOI18N
        guienviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guienviarActionPerformed(evt);
            }
        });

        guiLimitacion.setBackground(new java.awt.Color(0, 153, 153));
        guiLimitacion.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        guiLimitacion.setForeground(new java.awt.Color(0, 0, 0));
        guiLimitacion.setMajorTickSpacing(1);
        guiLimitacion.setMaximum(5);
        guiLimitacion.setMinimum(1);
        guiLimitacion.setPaintLabels(true);
        guiLimitacion.setPaintTicks(true);
        guiLimitacion.setValue(3);

        guiTiempo.setBackground(new java.awt.Color(0, 153, 153));
        guiTiempo.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        guiTiempo.setForeground(new java.awt.Color(0, 0, 0));
        guiTiempo.setMajorTickSpacing(1);
        guiTiempo.setMaximum(5);
        guiTiempo.setMinimum(1);
        guiTiempo.setPaintLabels(true);
        guiTiempo.setPaintTicks(true);
        guiTiempo.setToolTipText("");
        guiTiempo.setValue(3);

        guiNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNombreActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("N°Orden");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tabDeliveryLayout = new javax.swing.GroupLayout(tabDelivery);
        tabDelivery.setLayout(tabDeliveryLayout);
        tabDeliveryLayout.setHorizontalGroup(
            tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDeliveryLayout.createSequentialGroup()
                .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabDeliveryLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(guiLimitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(tabDeliveryLayout.createSequentialGroup()
                                .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                                        .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(guiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                                        .addComponent(jlabl2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(guiTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(guienviar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(1174, Short.MAX_VALUE))
        );
        tabDeliveryLayout.setVerticalGroup(
            tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDeliveryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabl2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(guiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiLimitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(guienviar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabDeliveryLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2348, Short.MAX_VALUE))
        );

        panelMenu.addTab("Delivery", tabDelivery);

        jPanel5.setBackground(new java.awt.Color(153, 51, 0));

        guiConversacion.setBackground(new java.awt.Color(204, 51, 0));
        guiConversacion.setColumns(20);
        guiConversacion.setRows(5);
        jScrollPane3.setViewportView(guiConversacion);

        jTextField1.setForeground(new java.awt.Color(0, 153, 153));

        guiEnviarOrden.setText("Enviar");

        guiEnviar1.setText("Enviar pedido");

        RecibirOrden.setText("Recibir Orden");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(guiEnviarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RecibirOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(guiEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guiEnviarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(RecibirOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2221, Short.MAX_VALUE))
        );

        panelMenu.addTab("tab6", jPanel1);

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jScrollPane4.setBackground(new java.awt.Color(0, 102, 102));

        jTextArea1.setBackground(new java.awt.Color(102, 102, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addGap(0, 1249, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2277, Short.MAX_VALUE))
        );

        panelMenu.addTab("tab7", jPanel4);

        jScrollPane1.setViewportView(panelMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiNombreActionPerformed

    private void guienviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guienviarActionPerformed
        //1. Lee datos GUI
        String nombre = guiNombre.getText();
        int velocidad = guiTiempo.getValue(); //getvalue le devuelve un entero
        int demorar = guiTiempo.getValue();
        //2. crear panelCorrededor;
        panelRepartidor nuevorepartidor = new panelRepartidor(nombre, velocidad, demorar); //contruir loa datos q cree
        //3. Agregar de panelcorrededor a ventanacarrera
        pedido.agregarRepartidor(nuevorepartidor);
    }//GEN-LAST:event_guienviarActionPerformed

    private void GuiBottonCargarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiBottonCargarOrdenActionPerformed
        FacturaBebidas FacturaCargada = null;

        JFileChooser ventana = new JFileChooser(); // Asi Creo mi ventana
        int opcion = ventana.showOpenDialog(null); //Para Cargar el archivo

        if (opcion == JFileChooser.APPROVE_OPTION) {
            try {
                File Restaurante = ventana.getSelectedFile(); //Lo que me regresa como la cerre
                FileInputStream canal = new FileInputStream(Restaurante);
                ObjectInput mood = new ObjectInputStream(canal); //Mode de escritura de objetos en este leo

                FacturaBebidas FacturaB = (FacturaBebidas) mood.readObject();

                mood.close();
                GuiTArDetalle.setText("Factura compra Bebidas");
                GuiTArDetalle.append("\n-Nombre:\n " + "----" + FacturaB.nombre);
                GuiTArDetalle.append("\n-Tipo bebida:\n " + "----" + FacturaB.TipoBebida);
                GuiTArDetalle.append("\n-Tamaño:\n " + "----" + FacturaB.Tamaño);
                GuiTArDetalle.append("\n-Medida:\n " + "----" + FacturaB.medida);
                GuiTArDetalle.append("\n-Precio:\n " + "----" + FacturaB.total);
                GuiTArDetalle.append("\n-Comida seleccionada" + "----" + FacturaB.comida);
            } catch (IOException | ClassNotFoundException e) { //Exepciones de que se fue la conexion etc;
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_GuiBottonCargarOrdenActionPerformed

    private void guiPezcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiPezcadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiPezcadoActionPerformed

    private void guiOrdenarAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiOrdenarAlmuerzoActionPerformed
        //System.out.println(GuiTxtNombre.getText());
        boolean validacion = false;
        String nombre = GuiTxtNombre.getText(); //lo guardo en una variable
        int medida = GuiSliderMedida.getValue();// Solo falta Imprimirlo
        // System.out.println(medida);
        String Tamaño = "";

        if (GuiRadioButtonGrande.isSelected()) { //Decidir  EL BOTTON RADIO
            Tamaño = GuiRadioButtonGrande.getText();
        } else if (GuiRadioButtonMediano.isSelected()) {
            Tamaño = GuiRadioButtonMediano.getText(); //El texto que tenga medidano
        } else if (GuiRadioButtonPequeño.isSelected()) {
            Tamaño = GuiRadioButtonPequeño.getText();

        }

        //Seleccion de comidas por checks
        String comida="";

        if(guiEnchiladas.isSelected()){
            comida += guiEnchiladas.getText()+", ";
            validacion = true;
        }
        //verifica de uno en uno si esta seleccionada agrega el texto para mostrar en la orden
        if(guiHuevosPanquequeTocinetas.isSelected()){
            comida += guiHuevosPanquequeTocinetas.getText()+", ";
            validacion = true;
        }
        if(guiHuevosSalchichaTostada.isSelected()){
            comida += guiHuevosSalchichaTostada.getText()+", ";
            validacion = true;
        }
        if(guiHuevosTostada.isSelected()){
            comida += guiHuevosTostada.getText()+", ";
            validacion = true;
        }
        if(guiPinto.isSelected()){
            comida += guiPinto.getText()+", ";
            validacion = true;
        }

        if(guiArrozPollo.isSelected()){
            comida += guiArrozPollo.getText()+", ";
            validacion = true;
        }
        if(guiLasana.isSelected()){
            comida += guiLasana.getText()+", ";
            validacion = true;
        }
        if(guiPezcado.isSelected()){
            comida += guiPezcado.getText()+", ";
            validacion = true;
        }
        if(guihamburgesa.isSelected()){
            comida += guihamburgesa.getText()+", ";
            validacion = true;
        }
        if(guiPollo.isSelected()){
            comida += guiPollo.getName()+", ";
            validacion = true;
        }

        //JOptionPane.showMessageDialog(null, Tamaño);
        // System.out.println(Tamaño);
        if((GuiTxtNombre.getText().length() != 0)&&(validacion!=false)){

            int tipoBebidaIndice = GuiComboxBebida.getSelectedIndex();
            String TipoBebida = (String) GuiComboxBebida.getSelectedItem();
            //Para que lo combierta en un String y asi optenga el Texto
            System.out.println(TipoBebida);
            FacturaBebidas compra = new FacturaBebidas(nombre, medida, Tamaño, tipoBebidaIndice,
                TipoBebida,comida);

            JFileChooser ventana = new JFileChooser(); // Asi Creo mi ventana
            int opcion = ventana.showSaveDialog(null); //Para guadar el archivo

            if (opcion == JFileChooser.APPROVE_OPTION) {
                try {
                    File Restaurante = ventana.getSelectedFile(); //Lo que me regresa como la cerre
                    FileOutputStream canal = new FileOutputStream(Restaurante);
                    ObjectOutput mood = new ObjectOutputStream(canal); //Modo de escritura de objetos

                    mood.writeObject(compra);
                    mood.close();

                } catch (IOException e) { //Exepciones de que se fue la conexion etc;
                    System.out.println(e);
                }
            }
        }else{
            NoNombre ventanaError = new NoNombre();
            ventanaError.setVisible(true);
            setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_guiOrdenarAlmuerzoActionPerformed

    private void guiHuevosPanquequeTocinetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiHuevosPanquequeTocinetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiHuevosPanquequeTocinetasActionPerformed

    private void BottonOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonOrdenActionPerformed

        //System.out.println(GuiTxtNombre.getText());
        String nombre = GuiTxtNombre.getText(); //lo guardo en una variable
        int medida = GuiSliderMedida.getValue();// Solo falta Imprimirlo
        boolean validacion = false;
        // System.out.println(medida);
        String Tamaño = "";

        if (GuiRadioButtonGrande.isSelected()) { //Decidir  EL BOTTON RADIO
            Tamaño = GuiRadioButtonGrande.getText();
        } else if (GuiRadioButtonMediano.isSelected()) {
            Tamaño = GuiRadioButtonMediano.getText(); //El texto que tenga medidano
        } else if (GuiRadioButtonPequeño.isSelected()) {
            Tamaño = GuiRadioButtonPequeño.getText();

        }

        //Seleccion de comidas por checks
        String comida="";

        if(guiEnchiladas.isSelected()){
            comida += guiEnchiladas.getText()+", ";
            validacion = true;
        }
        //verifica de uno en uno si esta seleccionada agrega el texto para mostrar en la orden
        if(guiHuevosPanquequeTocinetas.isSelected()){
            comida += guiHuevosPanquequeTocinetas.getText()+", ";
            validacion = true;
        }
        if(guiHuevosSalchichaTostada.isSelected()){
            comida += guiHuevosSalchichaTostada.getText()+", ";
            validacion = true;
        }
        if(guiHuevosTostada.isSelected()){
            comida += guiHuevosTostada.getText()+", ";
            validacion = true;
        }
        if(guiPinto.isSelected()){
            comida += guiPinto.getText()+", ";
            validacion = true;
        }

        if(guiArrozPollo.isSelected()){
            comida += guiArrozPollo.getText()+", ";
            validacion = true;
        }
        if(guiLasana.isSelected()){
            comida += guiLasana.getText()+", ";
            validacion = true;
        }
        if(guiPezcado.isSelected()){
            comida += guiPezcado.getText()+", ";
            validacion = true;
        }
        if(guihamburgesa.isSelected()){
            comida += guihamburgesa.getText()+", ";
            validacion = true;
        }
        if(guiPollo.isSelected()){
            comida += guiPollo.getName()+", ";
            validacion = true;
        }

        //JOptionPane.showMessageDialog(null, Tamaño);
        // System.out.println(Tamaño);
        if((GuiTxtNombre.getText().length() != 0)&&(validacion!=false)){

            int tipoBebidaIndice = GuiComboxBebida.getSelectedIndex();
            String TipoBebida = (String) GuiComboxBebida.getSelectedItem();
            //Para que lo combierta en un String y asi optenga el Texto
            System.out.println(TipoBebida);
            FacturaBebidas compra = new FacturaBebidas(nombre, medida, Tamaño, tipoBebidaIndice,
                TipoBebida,comida);

            JFileChooser ventana = new JFileChooser(); // Asi Creo mi ventana
            int opcion = ventana.showSaveDialog(null); //Para guadar el archivo

            if (opcion == JFileChooser.APPROVE_OPTION) {
                try {
                    File Restaurante = ventana.getSelectedFile(); //Lo que me regresa como la cerre
                    FileOutputStream canal = new FileOutputStream(Restaurante);
                    ObjectOutput mood = new ObjectOutputStream(canal); //Modo de escritura de objetos

                    mood.writeObject(compra);
                    mood.close();

                } catch (IOException e) { //Exepciones de que se fue la conexion etc;
                    System.out.println(e);
                }
            }
        }else{
            NoNombre ventanaError = new NoNombre();
            ventanaError.setVisible(true);

        }
    }//GEN-LAST:event_BottonOrdenActionPerformed

    private void guiHuevosSalchichaTostadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiHuevosSalchichaTostadaActionPerformed

    }//GEN-LAST:event_guiHuevosSalchichaTostadaActionPerformed

    private void guiHuevosTostadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiHuevosTostadaActionPerformed

    }//GEN-LAST:event_guiHuevosTostadaActionPerformed

    private void GuiComboxBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiComboxBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuiComboxBebidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonOrden;
    private javax.swing.ButtonGroup GrupoTamaño;
    private javax.swing.JButton GuiBottonCargarOrden;
    private javax.swing.JComboBox<String> GuiComboxBebida;
    private javax.swing.JLabel GuiLabelCliente1;
    private javax.swing.JLabel GuiLabelMedida;
    private javax.swing.JLabel GuiLabelTamaño;
    private javax.swing.JLabel GuiLabelTipoBebida;
    private javax.swing.JRadioButton GuiRadioButtonGrande;
    private javax.swing.JRadioButton GuiRadioButtonMediano;
    private javax.swing.JRadioButton GuiRadioButtonPequeño;
    private javax.swing.JSlider GuiSliderMedida;
    private javax.swing.JTextArea GuiTArDetalle;
    private javax.swing.JTextField GuiTxtNombre;
    private javax.swing.JButton RecibirOrden;
    private javax.swing.JLabel guiArrosPolloIma;
    private javax.swing.JCheckBox guiArrozPollo;
    private javax.swing.JTextArea guiConversacion;
    private javax.swing.JCheckBox guiEnchiladas;
    private javax.swing.JButton guiEnviar1;
    private javax.swing.JButton guiEnviarOrden;
    private javax.swing.JCheckBox guiHuevosPanquequeTocinetas;
    private javax.swing.JCheckBox guiHuevosSalchichaTostada;
    private javax.swing.JCheckBox guiHuevosTostada;
    private javax.swing.JCheckBox guiLasana;
    private javax.swing.JLabel guiLasanaIma;
    private javax.swing.JSlider guiLimitacion;
    private javax.swing.JTextField guiNombre;
    private javax.swing.JButton guiOrdenarAlmuerzo;
    private javax.swing.JCheckBox guiPezcado;
    private javax.swing.JLabel guiPezcadoIma;
    private javax.swing.JCheckBox guiPinto;
    private javax.swing.JCheckBox guiPollo;
    private javax.swing.JLabel guiPolloAzadoIma;
    private javax.swing.JSlider guiTiempo;
    private javax.swing.JButton guienviar;
    private javax.swing.JCheckBox guihamburgesa;
    private javax.swing.JLabel guihamburgesaIma;
    private javax.swing.JLabel huevosyTostada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlabl2;
    private javax.swing.JTabbedPane panelMenu;
    private javax.swing.JPanel tabAlmuerzo;
    private javax.swing.JPanel tabBebidas;
    private javax.swing.JPanel tabDelivery;
    private javax.swing.JPanel tabDesayuno;
    private javax.swing.JPanel tabFactura;
    // End of variables declaration//GEN-END:variables
}
