/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Diccionario;
import clases.Termino;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aboza
 */
public class NewDictionary extends javax.swing.JFrame {
    
    static ArrayList<Termino> NuevoSetTerminos;

    /**
     * Creates new form NewDictionary
     */
    public NewDictionary() {
        initComponents();
        NuevoSetTerminos = new ArrayList<Termino>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaConcept = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnSaveDictionary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaConcept.setColumns(20);
        txaConcept.setRows(5);
        jScrollPane1.setViewportView(txaConcept);

        btnSave.setText("Guardar Termino");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReturn.setText("Volver");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnSaveDictionary.setText("Guardar Diccionario");
        btnSaveDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDictionaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(txtWord)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSaveDictionary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveDictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Termino nuevoTermino = new Termino(txtWord.getText(), txaConcept.getText());
        this.NuevoSetTerminos.add(nuevoTermino);
        txtWord.setText("");
        txaConcept.setText("");
        JOptionPane.showMessageDialog(null, "Nuevo termino agregado");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDictionaryActionPerformed
        // TODO add your handling code here:
        if (!NuevoSetTerminos.isEmpty()) {
            Diccionario nuevoDiccionario = new Diccionario(NuevoSetTerminos);
            nuevoDiccionario.setTerminos(NuevoSetTerminos);
            Collections.sort(NuevoSetTerminos);
            GuardarDiccionario(nuevoDiccionario);
            
        } else {
            JOptionPane.showMessageDialog(null, "No ha agregado ningun termino");
        }

    }//GEN-LAST:event_btnSaveDictionaryActionPerformed
    
    private void GuardarDiccionario(Diccionario pDiccionario) {
        //VAMOS A PROCEDER PRIMERO A GUARDALO EN UN ARCHIVO            
        try {
            //PRIMERO NECESITAMOS CREAR EL FILEOUTPUTSTREAM PARA HACER REFERENCIA A NUESTRO ARCHIVO
            FileOutputStream miArchivo = new FileOutputStream("Diccionario.boza");//pueden colocar una direccion especifica

            //LUEGO NECESITAMOS CREAR EL OBJECTOUTPUTSTREAM
            ObjectOutputStream output = new ObjectOutputStream(miArchivo);

            //Y LUEGO VAMOS A ESCRIBIR NUESTROS OBJETOS EN EL ARCHIVO
            output.writeObject(pDiccionario);

            //RECORDEMOS CERRAR EL ARCHIVO LUEGO DE ESCRIBIR EN EL
            output.close();
            miArchivo.close();
            
            JOptionPane.showMessageDialog(null, "Se ha almacenado correctamente el nuevo diccionario");
            this.dispose();
            
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveDictionary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaConcept;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
