/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurante;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class BaseDadatos extends javax.swing.JFrame {

     private Connection conexion;
     private Statement envia;
     
    public BaseDadatos() {
        initComponents();
       
        try {
             conexion = DriverManager.getConnection("jdbc:derby://localhost:1527/Reservaciones", "administrador", "123");
            
             
             
             envia = conexion.createStatement();
         } catch (SQLException ex) {
             System.out.println("Error al ingresar a la base de datos "+ex);
             
             JOptionPane.showMessageDialog(null, "Error de coexion"+ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        guiIngresar = new javax.swing.JToggleButton();
        guiMostrarR = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        guiCabtidadPersonas = new javax.swing.JComboBox<>();
        guiFecha = new javax.swing.JTextField();
        guiHora = new javax.swing.JTextField();
        guiNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiIngresar.setText("Ingresar Reserva");
        guiIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(guiIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        guiMostrarR.setText("Mostrar Reservas");
        guiMostrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMostrarRActionPerformed(evt);
            }
        });
        jPanel1.add(guiMostrarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Personas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Hora:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 30));

        guiCabtidadPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel1.add(guiCabtidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, 30));
        jPanel1.add(guiFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 310, 30));
        jPanel1.add(guiHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 310, 30));
        jPanel1.add(guiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/Imagenes/valle-azul-resturant.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        guiTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fechas", "Hora", "Personas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(guiTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 361, 510, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiIngresarActionPerformed
        String nombre = guiNombre.getText();
             String hora = guiFecha.getText();
             String fecha = guiHora.getText();
             int cantidadPersonas =guiCabtidadPersonas.getSelectedIndex(); //inicia desde 0 el las opciones
        try {
            
            if((nombre.isEmpty() == false)&&(hora.isEmpty() == false)&&(fecha.isEmpty() == false) && (cantidadPersonas != 0)){
               String insertar = "INSERT INTO UNTITLED VALUES ('"+nombre+"',"
                     + "'"+hora+"','"+fecha+"',"+cantidadPersonas+")";
             envia.executeUpdate(insertar);
             guiCabtidadPersonas.setSelectedIndex(0);
             guiHora.setText("");
             guiFecha.setText("");
             guiNombre.setText(""); 
            }else{
                JOptionPane.showMessageDialog(null, "Tiene que completar todos los datos para hacer una reserva");
            }
             
             
            
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error al enviar datos a la base "+ex);
         }
         
         
    }//GEN-LAST:event_guiIngresarActionPerformed

    private void guiMostrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMostrarRActionPerformed
        
         try {
             ResultSet mostrar = envia.executeQuery("SELECT * FROM UNTITLED");
             
             DefaultTableModel informacionTabla = (DefaultTableModel)guiTabla.getModel();
             informacionTabla.setRowCount(0);
             
             while(mostrar.next()){
                 String nombre = mostrar.getString(1);
                 String fecha = mostrar.getString(2);
                 String hora = mostrar.getString(3);
                 int personas = mostrar.getInt(4);
                 informacionTabla.addRow(new Object[]{
                         
                     mostrar.getString("Nombre"),
                     mostrar.getString("Fecha"),
                     mostrar.getString("Hora"),
                     mostrar.getInt("Personas")
                         
                         
                         });
                 
             }
             
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error al mostrar en la tabla: "+ex);
             
         }
         
         
    }//GEN-LAST:event_guiMostrarRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseDadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseDadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseDadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseDadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseDadatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> guiCabtidadPersonas;
    private javax.swing.JTextField guiFecha;
    private javax.swing.JTextField guiHora;
    private javax.swing.JToggleButton guiIngresar;
    private javax.swing.JToggleButton guiMostrarR;
    private javax.swing.JTextField guiNombre;
    private javax.swing.JTable guiTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
